### ISSUE TITLE
ValueError on importing 1st repo

### ISSUE THREAD

**Issue by PetervdPerk** [MarcelSimon/MigrateGitlabToGogs#1]
Hey MarcelSimon your migration script looks pretty neat.

I've tried to migrate my repo's from Gitlab, detection and API calls are working fine.
However on the migration of the first repo I am getting this error:

Migrating project git@********.nl:PetervdPerk/GLT-Assign2.git to project GLT-Assign2 now.
Do you want to continue? (please answer yes or no) yes
Traceback (most recent call last):
  File "migrate_gitlab_to_gogs.py", line 107, in <module>
    print('Could not create repo %s because of %s'%(src_name,json.loads(create_repo.text)['message']))
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

**Comment by MarcelSimon** [comment]
It seems there was a problem with creating a repository. Maybe it already exists in gogs? The ValueError seems to occur when printing the error message, not sure why this happens though. Are the API keys correct? Maybe check that again
